Clarify required imports, fix default formatter for describe
I thought it confusing to have only the "import chrono" as the start and thought it was a copy/paste issue, so thought I would clarify the comment and explicitly add the "polars" prelude.

I also noticed that upon enabling the feature "describe" the example didn't work unless I use the `{:?}` pretty-print

```
error[E0277]: `Result<polars::prelude::DataFrame, PolarsError>` doesn't implement `std::fmt::Display`
  --> src/main.rs:53:20
   |
53 |     println!("{}", df.describe(None));
   |                    ^^^^^^^^^^^^^^^^^ `Result<polars::prelude::DataFrame, PolarsError>` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `Result<polars::prelude::DataFrame, PolarsError>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)
```